# Generated by Django 5.1.5 on 2025-04-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_newslettersignup_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersignup',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
