# Generated by Django 5.1.2 on 2025-04-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='session',
            field=models.CharField(blank=True, choices=[('morning', 'Morning Session – 6:00 AM to 10:00 AM'), ('afternoon', 'Afternoon Session – 12:00 PM to 4:00 PM'), ('evening', 'Evening Session – 5:00 PM to 9:00 PM')], max_length=20, null=True),
        ),
    ]
