# Generated by Django 5.1.2 on 2025-05-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_paymentqrcode_payment_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
